### ISSUE TITLE
Erro ao publicar mensagem Kafka

### ISSUE THREAD

**Issue by fabianosanttana** [codeedu/imersao8#2]
Olá pessoal, estou com um erro ao publicar a mensagem pelo GO
Parece ser por causa do host.docker.internal:172.17.0.1

`producer := kafka.NewKafkaProducer()
  kafka.Publish("olá", "readtest", producer)`

Adicionei a linha 
127.0.0.1 host.docker.internal no meu etc/hosts mas está dando timeout.
@wesleywillians @argentinaluiz 

`%3|1655827555.464|FAIL|rdkafka#producer-1| [thrd:host.docker.internal:9094/bootstrap]: host.docker.internal:9094/bootstrap: Connect to ipv4#172.17.0.1:9094 failed: Connection timed out (after 130166ms in state CONNECT)`

**Comment by Victor7095** [comment]
Também estou tendo esse erro.
SO: Windows 10 (WSL 2)

**Comment by tiago-buso** [comment]
Também estou com mesmo erro

**Comment by argentinaluiz** [comment]
Oi pessoal, tudo bem?

Vocês adicionaram isto no `docker-compose.yaml` da aplicação Golang?

[https://github.com/codeedu/imersao8/blob/main/simulator/docker-compose.yaml#L9-L10](https://github.com/codeedu/imersao8/blob/main/simulator/docker-compose.yaml#L9-L10).

Para o `host.docker.internal` funcionar é necessário realizar esta configuração.

**Comment by fabianosanttana** [comment]
Aqui eu consegui fazer funcionar, mesmo adicionando a linha do host internal no etc/host
só funcionou depois que eu adicionei o projeto go na mesma network do kafka

`docker-compose.yaml`

```
version: "3"

services:
  app:
    networks:
      - default
    build: .
    container_name: simulator
    volumes:
      - .:/go/src
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

networks:
  default:
    external:
      name: kafka_default
```

Sem esta configuração da network, nada que eu tentei funcionou aqui no macOS.

**Comment by Victor7095** [comment]
@argentinaluiz já tinha adicionado este trecho:
```
extra_hosts:
      - "host.docker.internal:172.17.0.1"
```
@fabianosanttana Realmente, com isso agora funcionou, vlw! 👍

**Comment by tiago-buso** [comment]
> Aqui eu consegui fazer funcionar, mesmo adicionando a linha do host internal no etc/host só funcionou depois que eu adicionei o projeto go na mesma network do kafka
> 
> `docker-compose.yaml`
> 
> ```
> version: "3"
> 
> services:
>   app:
>     networks:
>       - default
>     build: .
>     container_name: simulator
>     volumes:
>       - .:/go/src
>     extra_hosts:
>       - "host.docker.internal:172.17.0.1"
> 
> networks:
>   default:
>     external:
>       name: kafka_default
> ```
> 
> Sem esta configuração da network, nada que eu tentei funcionou aqui no macOS.

Consegui utilizando essas dicas no Windows 11 com WSL2. Obrigado!

Também percebi que tinha esquecido de alterar o arquivo hosts. No meu caso notei que já existia um "host.docker.internal" com um outro ip e que foi adicionado pelo Docker Desktop. Deixei a linha com o ip localhost no final do arquivo hosts, provavelmente estou fazendo override dessa configuração.

Depois de fazer essa alteração no hosts e de adicionar essa Network (o comando do Dockerfile que o Luiz indicou eu já tinha feito), tive que derrubar os containers e criá-los novamente (docker-compose down em ambos os terminais, do GO e do Kafka).

Quando subi o conteiner do go (simulator) reparei que deu erro na primeira vez, reclamou de não conseguir criar a network externa, mas rodando novemente deu certo e rodando o comando docker network ls a nova rede está lá.

EDIT:

Só esqueci de comentar que todos os host.docker.internal:172.17.0.1 ficaram desse jeito mesmo.

**Comment by argentinaluiz** [comment]
Show pessoal, ótimo que conseguiram evoluir!

Qualquer dúvida, estamos à disposição.

**Comment by moreiralud** [comment]
nossa, eu estou passando pelo mesmo erro. Já adicionei host na pasta `etcs/hosts `e continuo recebendo:

`%3|1676066051.462|FAIL|rdkafka#producer-1| [thrd:host.docker.internal:172/bootstrap]: host.docker.internal:172/bootstrap: Connect to ipv4#127.0.0.1:172 failed: Connection refused (after 0ms in state CONNECT, 30 identical error(s) suppressed)`

as configs do `docker-compose.yml`

```
version: "3"

services:
  app:
    networks:
      - default
    build: .
    container_name: simulator
    volumes:
      - .:/go/src
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

networks:
  default:
    external:
      name: kafka_default
```

as configs do` kafka/docker-compose.yaml`:
```

version: "3"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  kafka-topics-generator:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    command: >
      bash -c
        "sleep 5s &&
        kafka-topics --create --topic=route.new-direction --if-not-exists --bootstrap-server=kafka:9092 &&
        kafka-topics --create --topic=route.new-position --if-not-exists --bootstrap-server=kafka:9092"
  control-center:
    image: confluentinc/cp-enterprise-control-center:6.0.1
    hostname: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_CONNECT_CLUSTER: http://kafka-connect:8083
      PORT: 9021
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
```

dei `docker-compose down`, depois up de novo no container e mesmo assim não consigo.

*esqueci de mencionar que estou usando ubuntu.


**Consegui resolver. Era o arquivo .env que tava com o host errado. Coloquei 9094 deu certo.**
